### PR TITLE
Use Gradle to build project

### PR DESCRIPTION
**Pull request by andrewda**
With GradleRIO being the official build system for 2019+, it would be great to use Gradle to build this project. With this, implementing badlog into a robot is as easy as adding

```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile "com.github.dominikWin:badlog:v0.1.0"
}
```

to the build.gradle file. Significantly easier and cleaner than adding a JAR to an external `libs` directory and importing those through Gradle.

### CODE REVIEW

**Comment by dominikWin** [comment]
Thanks! This is really good

**Comment by maniyar1** [comment]
Was this tested? Jitpack is spitting out an [error log](https://jitpack.io/com/github/dominikWin/badlog/v0.1.0/build.log) that it can't find the gradle build file.

**Comment by andrewda** [comment]
@maniyar1 Apologies, I should have made that more clear. v0.1.0 doesn't have a Gradle file because it was released before this PR was merged. Before the next release, you can use this:

```
dependencies {
    compile "com.github.dominikWin:badlog:4f1644c35e929020cf1362b89a4f8187efd7ebe3"
}
```

Just tested that on our codebase and it's working 👍

**Comment by maniyar1** [comment]
Oh yeah, that did end up working. But is there a reason why the repository doesn't have a gradle-wrapper.jar? I feel like it might have been stolen by the .gitignore.

**Comment by andrewda** [comment]
Good catch, yep that looks like what happened. #2 should fix 👍

**Pull request merged**
